### ISSUE TITLE
The link for the PySystemCoupling doc is throwing a 404 error.

### ISSUE THREAD

**Issue by PipKat** [pyansys/pysystem-coupling#137]
### Description of the modifications

I'm not sure if the 404 error is a result of recent action changes, but clicking the link for the doc on the repo page is throwing an error--as well as pasting this link in a browser's address bar.

**Comment by iboyd-ansys** [comment]
I am not sure why this started happening but @Revathyvenugopal162 merged a fix to gh-pages for this today. The link is working now.

**Comment by PipKat** [comment]
@iboyd-ansys Glad the issue is resolved. Kelly Fletcher contacted me late Friday because the link was broken.
